CREATE TABLE player (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    profile_image BYTEA DEFAULT NULL,
    wins INT NOT NULL,
    last_heartbeat TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE card (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value_left VARCHAR(255) NOT NULL,
    value_right VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE room (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_active_player_id INT DEFAULT NULL,
    game_active_card_id INT DEFAULT NULL,
    uuid UUID NOT NULL,
    password VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    game_state VARCHAR(255) DEFAULT NULL,
    game_points_team_a INT DEFAULT NULL,
    game_points_team_b INT DEFAULT NULL,
    game_round_index INT DEFAULT NULL,
    game_target_degree DOUBLE PRECISION DEFAULT NULL,
    game_cluegiver_guess_text VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(id),
    CONSTRAINT FK_729F519BB16171F7 FOREIGN KEY (game_active_player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT FK_729F519B134A7A72 FOREIGN KEY (game_active_card_id) REFERENCES card (id) NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_729F519BB16171F7 ON room (game_active_player_id);
CREATE INDEX IDX_729F519B134A7A72 ON room (game_active_card_id);

CREATE TABLE guess (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id INT NOT NULL,
    room_id INT NOT NULL,
    degree DOUBLE PRECISION NOT NULL,
    is_preview BOOLEAN NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT FK_32D30F9699E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT FK_32D30F9654177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_32D30F9699E6F5DF ON guess (player_id);
CREATE INDEX IDX_32D30F9654177093 ON guess (room_id);

CREATE TABLE room_players_team_a (
    room_id INT NOT NULL,
    player_id INT NOT NULL,
    PRIMARY KEY(room_id, player_id),
    CONSTRAINT FK_CBBE562B54177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT FK_CBBE562B99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_CBBE562B54177093 ON room_players_team_a (room_id);
CREATE INDEX IDX_CBBE562B99E6F5DF ON room_players_team_a (player_id);

CREATE TABLE room_players_team_b (
    room_id INT NOT NULL,
    player_id INT NOT NULL,
    PRIMARY KEY(room_id, player_id),
    CONSTRAINT FK_52B7079154177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT FK_52B7079199E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_52B7079154177093 ON room_players_team_b (room_id);
CREATE INDEX IDX_52B7079199E6F5DF ON room_players_team_b (player_id);

CREATE TABLE room_card (
    room_id INT NOT NULL,
    card_id INT NOT NULL,
    PRIMARY KEY(room_id, card_id),
    CONSTRAINT FK_751072B754177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT FK_751072B74ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_751072B754177093 ON room_card (room_id);
CREATE INDEX IDX_751072B74ACC9A20 ON room_card (card_id);

INSERT INTO card (value_left, value_right) VALUES
    ('Good', 'Bad'),
    ('Highly addictive', 'Mildly addictive'),
    ('Cold', 'Hot'),
    ('Weird', 'Normal'),
    ('Colorful', 'Colorless'),
    ('High calorie', 'Low calorie'),
    ('Feels good', 'Feels bad'),
    ('Essential', 'Inessential'),
    ('Expensive', 'Cheap'),
    ('Overrated weapon', 'Underrated weapon'),
    ('Common', 'Rare'),
    ('Hard subject', 'Easy subject'),
    ('Famous', 'Unknown'),
    ('Easy to use', 'Difficult to use'),
    ('Weird', 'Normal'),
    ('Clean', 'Dirty'),
    ('Requires skill', 'Requires luck'),
    ('Flavorful', 'Flavorless'),
    ('Fascinating topic', 'Boring topic'),
    ('Good actors', 'Bad actor'),
    ('Hipster', 'Basic'),
    ('Safe job', 'Dangerous job'),
    ('Sci-Fi', 'Fantasy'),
    ('Formal', 'Casual'),
    ('Overpaid', 'Underpaid'),
    ('Wet', 'Dry'),
    ('Overrated skill', 'Underrated skill'),
    ('Encouraged', 'Forbidden'),
    ('Happy song', 'Sad song'),
    ('Durable', 'Fragile'),
    ('Best day of the year', 'Worst day of the year'),
    ('Good habit', 'Bad habit'),
    ('Dog person', 'Cat person'),
    ('Talented', 'Untalented'),
    ('Easy to remember', 'Hard to remember'),
    ('Healthy', 'Unhealthy'),
    ('Hairy', 'Hairless'),
    ('Flexible', 'Inflexible'),
    ('Exotic pet', 'Normal pet'),
    ('Extrovert', 'Introvert'),
    ('Movie was better', 'Book was better'),
    ('Good movie', 'Bad movie'),
    ('Beautiful', 'Ugly'),
    ('Happens suddenly', 'Happens slowly'),
    ('Hated', 'Loved'),
    ('Utopia', 'Dystopia'),
    ('Overrated thing to own', 'Underrated thing to own');
