-- Bootstrap your database with this script

CREATE TABLE entity_question (id SERIAL NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, PRIMARY KEY(id));
CREATE TABLE entity_room (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, starting_hitpoints INT NOT NULL, moderation_password VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE TABLE entity_round (id SERIAL NOT NULL, entity_room_id INT NOT NULL, round_counter INT NOT NULL, active_user_name VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_691ADFCDC7DA42B0 ON entity_round (entity_room_id);
CREATE TABLE entity_round_question (id SERIAL NOT NULL, entity_question_id INT NOT NULL, entity_round_id INT NOT NULL, entity_user_id INT DEFAULT NULL, user_answer_action VARCHAR(255) DEFAULT NULL, user_answer_custom_text TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_E2D711939C1DAC6C ON entity_round_question (entity_question_id);
CREATE INDEX IDX_E2D711934F4E0E0 ON entity_round_question (entity_round_id);
CREATE INDEX IDX_E2D7119334A3E1B6 ON entity_round_question (entity_user_id);
CREATE TABLE entity_round_vote (id SERIAL NOT NULL, entity_round_id INT NOT NULL, entity_user_id INT NOT NULL, ip VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_CD0986924F4E0E0 ON entity_round_vote (entity_round_id);
CREATE INDEX IDX_CD09869234A3E1B6 ON entity_round_vote (entity_user_id);
CREATE TABLE entity_user (id SERIAL NOT NULL, entity_room_id INT NOT NULL, name VARCHAR(255) NOT NULL, hitpoints INT NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_C55F6F62C7DA42B0 ON entity_user (entity_room_id);
ALTER TABLE entity_round ADD CONSTRAINT FK_691ADFCDC7DA42B0 FOREIGN KEY (entity_room_id) REFERENCES entity_room (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entity_round_question ADD CONSTRAINT FK_E2D711939C1DAC6C FOREIGN KEY (entity_question_id) REFERENCES entity_question (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entity_round_question ADD CONSTRAINT FK_E2D711934F4E0E0 FOREIGN KEY (entity_round_id) REFERENCES entity_round (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entity_round_question ADD CONSTRAINT FK_E2D7119334A3E1B6 FOREIGN KEY (entity_user_id) REFERENCES entity_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entity_round_vote ADD CONSTRAINT FK_CD0986924F4E0E0 FOREIGN KEY (entity_round_id) REFERENCES entity_round (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entity_round_vote ADD CONSTRAINT FK_CD09869234A3E1B6 FOREIGN KEY (entity_user_id) REFERENCES entity_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE entity_user ADD CONSTRAINT FK_C55F6F62C7DA42B0 FOREIGN KEY (entity_room_id) REFERENCES entity_room (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

INSERT INTO entity_question (question, answer) VALUES
('Was ist die Hauptstadt von Deutschland?','Berlin'),
('Was ist der Sinn des Lebens?','42'),
('Wieviele Kontinente gibt es?','7'),
('Was ist die größte Stadt der Welt? (Einwohner)','Tokio'),
('Wieviele Planeten gibt es in unserem Sonnensystem?','8'),
('Was ist die chemische Formel für Wasser?','H2O'),
('Wieviele Bundesländer hat Deutschland?','16'),
('Welcher Fluss ist der längste Fluss der Welt?','Nil'),
('Wieviele Zähne hat ein Mensch?','32'),
('Was ist die kleinste Einheit des Lebens?','Die Zelle'),
('Wieviele Farben hat der Regenbogen?','7'),
('Was ist die Hauptstadt von Frankreich?','Paris'),
('Wieviele Tage hat ein Jahr?','365'),
('Wieviele Tage hatte das Jahr 2012?','366'),
('Was bedeutet die Abkürzung BIP in der Wirtschaft?','Brutto-Inlands-Produkt'),
('Welche Aufgabe hat die Bundesversammlung in Deutschland?','Die Wahl des Bundespräsidenten'),
('Welches Land trat als erstes Mitglied aus der europäischen Union aus?','Vereinigtes Königreich'),
('Wofür steht die Abkürzung CDU?','Christlich Demokratische Union Deutschlands'),
('Welcher Automobilhersteller hat den Slogan "Das Auto"?','Volkswagen'),
('Wofür steht die Abkürzung EKG?','Elektrokardiogram'),
('Nenne ein Hormon welches von der Bauchspeicheldüse produziert wird?','Insulin oder Glukagon'),
('Wie heißt die größte Aterie des menschlichen Körpers?','Die Aorta'),
('Wie heißt der wichtigste Atemmuskel unserers Körpers','Zwerchfell'),
('Was ist der Hauptauslöser für eine chronisch obstruktive Lungenerkrankung sowie für Lungenkrebs?','Rauchen'),
('Welches Mythologische Wesen ist halb Mensch halb Stier und lebte in der Sage nach in dem Labyrith von Kreta?','Minotaurus'),
('Das Christentum hat die Kirche, der Buddhismus hat Tempel und das Judentum die?','Synagoge'),
('Wie heißt die Welt der Menschen in der nordischen Mythologie?','Midgard'),
('Wie heißt das Gesetz von Ursache und Wirkung im Hinduismus, welches besagt, dass jede Handlung Konsequenzen hat?','Karma'),
('Wer flog laut griechischer Mythologie aus Hochmut zu nah an die Sonne und verbrannte so seine Flügel?','Icarus'),
('Welches Tier wird häufig mit der ägyptischen Göttin Bastet assoziiert?','Katze'),
('In welchem Land liegt der höchste Berg Afrikas der Kilimanjaro','Tansania'),
('Welcher Fluss fließt durch die Hauptstadt Ägyptens?','Der Nil'),
('Wie heißt die Insel auf der die Freiheitsstatue steht?','Liberty Island'),
('In welchem Gewässer liegt der Mariannengraben?','Pazifik'),
('Wie heißt die größte Insel Deutschlands','Rügen'),
('Wie heißt der Fluss welcher durch London fließt?','Themse'),
('Wie heißt das flächemäßig größte Land Südamerikas?','Brasilien'),
('Wie nennt man die natürliche Zerstörungen und Abtragung von Land durch Wind und Wasser?','Erosion'),
('Wie heißt das größte und schwerste Lebewesen der Welt?','Blauwal'),
('Zu etwa wieviel Prozent besteht unsere Luft aus Sauerstoff?','21%'),
('In welcher Serie spielt Brian Cranston einen Chemielehrer der anfängt Drogen herzustellen?','Breaking Bad'),
('Wie heißt der Junge der niemals erwachsen werden will und im Nimmerland lebt?','Peter Pan'),
('Wie nennt man die große grüne Fläche in New York City, die als Lunge der Stadt bezeichnet wird?','Central Park'),
('Das mittlerweile hierzulande kommerzialisierte Holy Fest der Farben kommt ursprünglich aus welchem Land?','Indien'),
('Welches mittlerweile in Deutschland beheimatete Tier ist gemeint wenn man Canis Lupus spricht?','Wolf'),
('Wie heißen die Bausteinen von Proteinen?','Aminosäuren'),
('Wie heißt der Prozess bei dem Pflanzen Sonnenlicht in Energie umwandeln?','Photoynthese'),
('Mithilfe welchen Gerätes kann man sich auf Grund des Erdmagnetfeldes orientieren?','Kompass'),
('Wie heißt das Element im Periodensystem mit der Ordnungszahl 1?','Wasserstoff'),
('Wie nennt man die Energie die benötigt wird um eine chemische Reaktion zu starten?','Aktivierungsenergie'),
('Welcher Grunge Band gehörte der legendäre Frontmann Kurt Cobain an?','Nirvana'),
('Bei welchem ph-Wert spricht man von neutral?','7'),
('Im Atomkern befinden sich neben den Neutronen auch positiv geladenen Teilchen wieder. Wie heißen diese?','Protonen'),
('Wieviel Volt hat eine normale Haushaltssteckdose in Deutschland durchschnittlich?','230V'),
('Welcher Künstler wird als King von Rock"n"Roll oder auch als The King bezeichnet?','Elivs Presley'),
('Von welcher Band sind Songs wie "Back in Black", "TNT" oder "Thunderstruck"?','AC/DC'),
('Wie nennt man die längste Seite eines rechtwinkligen Dreiecks?','Hypothenuse'),
('Nenne Pi mit bis zu 2 Nachkommstellen','3.141'),
('Wie bezeichnet man eine mathematische Funktion die immer die gleiche Steigung hat?','Eine lineare Funktion'),
('Welches soziale Netzwerk kaufte Elon Musk 2022 für 44 Milliarden Dollar?','Twitter'),
('Welches chemische Element wird zur Herstellung von Bleistiftminen verwendet?','Kohlenstoff (in Form von Graphit)'),
('Wie heißt die Hauptstadt von Peru?','Lima'),
('Aus welcher Pflanze wird Tequilla hergestellt?','Agave'),
('Wofür steht die Abkürzung StGB im deutschen Recht?','Strafgesetzbuch'),
('Wo befindet man sich wenn man am LHR landet?','Flughafen London Heathrow'),
('Woraus wird Marzipan hergestellt?','Nüssen (Mandeln) und Zucker'),
('Welche Cryptowährung wurde als erste entwickelt und erlangte große Popularität?','Bitcoin'),
('Wie heißt die Währung in Japan?','Yen'),
('Wieviele Pferde sind dem Streitwagen auf dem Brandenburger Tor vorgespannt?','4'),
('Wieviele Felder hat ein Schachbrett','8'),
('In welche Richtung beten Muslime','Mekka'),
('Wie kürzt man Desoxyribonukleinsäure ab?','DNS oder DNA'),
('Wie nennt man 2 Geraden die sich niemals schneiden?','Parallelen'),
('Was will Gru aus dem ersten Teil von Ich einfach unverbesserlich mithilfe siner Minions stehlen?','Den Mond'),
('Mit welcher Einheit wird die Schärfe von z.B. Chilischoten gemessen?','Scoville'),
('In welchem Land gelten Pelmeni als Nationalgericht','Russland'),
('Die Sachertorte gilt als Schokoladige Spezialität welcher Stadt?','Wien'),
('Bilde den Plural von Matrix','Matrizes'),
('Was ist der Hauptbestandteil von Hummus?','Kichererbsen'),
('In welcher Stadt bist du, wenn du auf der Spanischen Treppe stehst?','Rom'),
('Welche Krankheit war auf Piratenschiffen weit verbreitet?','Skorbut'),
('Welche Tiere sind die einzigen Säugetiere die fliegen können?','Fledermäuse'),
('Wie hieß der erste Mensch der im Weltraum war?','Juri Alexejewitsch Gagarin'),
('Wie heißt das berühmte Gefängnis, welches auf einer Insel vor San Fransisco liegt?','Alcatraz'),
('Auf welchen berühmten Schriftsteller geht das Zitat "Sein oder Nichtsein, das ist hier die Frage" zurück?','Shakespear'),
('Wie heißt der Zwergplanet der früher als 9ter Planet galt?','Pluto'),
('Wie nennt man eine Sternenexplosion?','Supernova'),
('Wie heißt der Sonnen-nächste Planet unseres Sonnensystems?','Merkur'),
('In welchem Museum kann man die Mona Lisa bestaunen?','Louvre'),
('Woführ steht die Abkürzung des Musikstils RnB?','Rythm and Blues'),
('Welchem Vogel ist es möglich rückwärts zu fliegen?','Kolibri'),
('Welche Unterwasserpflanzen nutzt der Clownfisch gerne als Zuhause?','Anemone'),
('Wie wird versteinertes Baumharz genannt?','Bernstein'),
('Welche Süßigkeit wird aus der Süßholzwurzel hergestellt?','Lakritz'),
('Zum Nachweis welchen Stoffes gilt die Knallgas-Probe?','Wasserstoff'),
('Welches Element kommt in allen organischen Verbindungen vor?','Kohlenstoff'),
('Was misst ein Barometer?','Luftdruck'),
('Welches Land hat den Spitznamen "Land der aufgehenden Sonne"?','Japan'),
('Welcher Staat der USA ist bekannt als "Sunshine-State"','Florida'),
('Wieviele Länder grenzen an Finnland?','3 (Norwegen, Schweden, Russland)'),
('Wecher irische Feiertag wird stark mit der Farbe grün asszoiiert?','Saint Patrick"s Day'),
('Was ist die sogenannte Braille-Schrift?','Blindenschrift'),
('Wie heißt die Buchstabenschrift die in Russland verwendet wird?','Kyrillische Schrift'),
('Welche Muttersprache hat die meisten Muttersprachler in Europa?','Deutsch'),
('Wer hält den aktuellen Weltrekord über 100m mit 9.58 Sekunden?','Usain Bolt'),
('Wie lautet die erste Regel des Fight Club?','Man spricht nicht über den Fight Club'),
('Wie heißt der Hauptcharakter in Minecraft?','Steve'),
('Wie nennt man die Sprache die eigens für die Sims konstruiert wurde?','Simlish'),
('In welchem Jahr wurde die UNO gegründet? ','1945'),
('Wie viele Elemente gibt es im Periodensystem?','118'),
('Wie lautet der 4. Buchstabe des griechischen Alphabets?','Delta'),
('Wer hat entdeckt, dass sich die Erde um die Sonne dreht?','Nikolaus Kopernikus'),
('Kratos ist die Hauptfigur welcher Videospielreihe?','God of War'),
('Welches Land hat die meisten Fußballweltmeisterschaften gewonnen?','Brasilien'),
('In welchem Land liegt das Kernkraftwerk Tschernobyl?','Ukraine'),
('Wie heißt der Modus in League of Legends bei dem 5v5 auf nur einer Lane gespielt wird?','ARAM'),
('Wie heißt der fliegende Lemur aus der Serie Avatar: Der Herr der Elemente','Momo'),
('Wie heißt der Protagonist aus The Legend of Zelda','Link'),
('Wer oder was ist Epona aus The Legend of Zelda?','Ein Pferd'),
('Wofür steht WiFi','Wireless Fidelity'),
('Welche Programmiersprache wurde von James Gosling entwickelt und ist bekannt für ihre Platformunabhägigkeit?','Java'),
('Was sind sogenannte NPC"s im Gaming?','Non player character'),
('Wofür steht die Abkürzung GG (Großbuchstaben)','Grundgesetz'),
('In welcher Stadt findet die Gamescom statt?','Köln'),
('Wofür steht die Abkürzung CPU?','Central Processing Unit'),
('Wafür steht die Abkürzung GTA?','Grand Theft Auto'),
('Wie lautet der Name des Hauptcharakters in The Witcher?','Geralt von Riva'),
('If there is something strange in your neighborhood, who you gonna call?','Ghostbusters'),
('Wie heißt die Heimatwelt der Navi in Avatar?','Pandorra'),
('Wie heißt die Spielwährung in Fortnite?','V-Bucks'),
('Welches tollpatschige Pokemon leidet unter Kopfschmerzen?','Enton'),
('In welcher Stadt steht eine 3m hohe Godzilla-Statue?','Tokio'),
('Wie lautet Harry Potter"s 2ter Vorname?','James'),
('Wie heißt der Planet auf dem Luke Skywalker aufwächst?','Tatooine'),
('Welcher Superheld ist Trägers des Hammers Mjölnir?','Thor'),
('Wie lautet der Superheldenname von Peter Parker?','Spiderman'),
('Wie heißt der Planet auf dem Superman geboren wurde?','Krypton'),
('Welchen Beruf üben Mario und sein Bruder Luigi aus?','Anlagenmechaniker für Sanitär-, Heizungs- und Klimatechnik'),
('Wer entführt ständig Prinzessin Peach?','Bowser'),
('Wieviele Knochen hat ein erwachsener Körper?','206'),
('Was ist der RAM bei einem Computer?','Arbeitsspeicher'),
('Wie heißt der größte Ozean der Welt?','Pazifischer Ozean'),
('Welcher Planet ist der zweitnächste zur Sonne?','Venus'),
('Wieviele Spieler hat eine Fußballmannschaft auf dem Feld?','11'),
('In welchem Jahr endete der 2te Weltkrieg?','1945'),
('Wieviele Tasten hat ein klassisches Klavier?','88'),
('Was ist das chemische Symbol für Gold?','Au'),
('Welche Stadt ist die Hauptstadt von Australien?','Canberra'),
('Welche ist die am häufigsten gesprochene Muttersprache der Welt?','Mandarin'),
('Welcher Kontinent hat die meisten Länder?','Afrika'),
('Wieviele Ringe hat das olympische Logo?','5'),
('Wie heißt die Hauptstadt von Kanada?','Ottawa'),
('Welches Land ist flächenmäßig das Größte der Welt?','Russland'),
('Wieviel ist 56 x 2?','112'),
('Wie heißt die Hauptstadt von Griechenland?','Athen'),
('Wie heißt der höchste Berg der Erde?','Mount Everest'),
('Welches ist das südlichste Land in Afrika?','Südafrika'),
('Welcher US-Bundesstaat hat die meisten Einwohner?','Kalifornien'),
('Wie heißt die Landeshauptstadt von Rheinland-Pfalz?','Mainz'),
('Was bekämpfen Antibiotika?','Bakterien'),
('Ein Synony für echauffieren lautet?','Sich aufregen/beschweren'),
('Welches Süßungsmittel wird normalerweise in Diet-Coke verwendet?','Aspartam'),
('In Belgien wird die Sprache Belgisch gesprochen. Wahr oder falsch?','Falsch'),
('Wieviel Kubikzentimeter sind in einem halben Liter?','500'),
('Zebras werden ohne Streifen geboren. Wahr oder falsch?','Falsch'),
('An wieviele Länder grenzt Deutschland?','9'),
('Wo geht die Sonne unter?','Im Westen'),
('In welcher Zeitepoche lebten die Ritter?','Im Mittelalter'),
('Wie nennt man die Schwester der Mutter?','Tante'),
('Wieviele Beine haben 3 Spinnen zusammen?','24'),
('Wie heißen die eiförmigen elektronischen Haustiere aus Japan?','Tamagotchi'),
('Was ist der flächenmäßig größte Kontinent?','Asien'),
('Für was ist Magnus Carlsen bekannt?','Schach'),
('In welchem Land liegt die Stadt Stockholm?','Schweden'),
('Wer war der erste deutsche Bundeskanzler?','Konrad Adenauer'),
('Was heißt Niere auf Englisch?','Kidney'),
('Was heißt Vamos a la playa auf Deutsch?','Wir gehen zum Strand'),
('Für was steht IQ?','Intelligenzquotient'),
('Zu welchem Kontinent gehört Dubai?','Asien'),
('Für was steht NATO?','North Atlantic Treaty Organization'),
('Für was steht die Abkürzung des Spiels D&D?','Dungeons and Dragons'),
('Von wem ist der Song Bauch, Beine, Po?','Shirin David'),
('Ein Frosch ist ein Reptil. Wahr oder Falsch?','Falsch'),
('Wofür steht die Abkürzung SBMM im Gaming?','Skill Based Matchmaking'),
('Wie wird Ethanol umgangssprachlich bezeichnet?','Alkohol'),
('Ab wieviel Promille darf man kein Auto mehr fahren nach der Probezeit?','0.5 Promille'),
('In welcher Stadt steht der Big Ben?','London'),
('Wann war der Mauerfall?','1989 (9-10 November)'),
('Wann fing der Bau der Berliner Mauer an?','1961'),
('Welche Stadt hat das Kennzeichen H?','Hannover'),
('Wie heißt der längste Tag des Jahres?','Sommersonnenwende'),
('Wie nennt sich die Gruppe der Elemente mit gesättigter Außenschale?','Edelgase'),
('Natrium gehört zu den Alkali-Metallen. Wahr oder falsch?','Wahr'),
('Wo fand die EM 2024 statt?','Deutschland'),
('Wofür steht das E am Ende eines kennzeichens?','Elektrofahrzeug'),
('Der Hexcode 000000 steht für welche Farbe?','Schwarz'),
('Welches Land hat als einziges eine quadratische Flagge?','Die Schweiz'),
('Welcher Fluss fließt durch Paris?','Die Seine'),
('Wer hat die Mona Lisa gemalt?','Leonardo DaVinci'),
('Welches ist das flächenmäßig kleinste Land der Welt?','Vatikanstadt'),
('Was ist der größte Knochen im menschlichen Körper?','Oberschenkelknochen/Femur'),
('Wie lautet der name der größten Insel der Welt?','Grönland'),
('Wofür steht die Abkürzung NASA?','National Aeronautics and Space Administration'),
('Welcher Tag ist der Star Wars Tag?','4ter Mai'),
('Wer spielte Iron Man im MCU?','Robert Downey Jr.'),
('Was ist der Hauptbestandteil von Tofu?','Soja'),
('Was ist die Hauptzutat von ein Mojito-Cocktail?','Rum'),
('Welches ist das schwerste innere Organ des menschlichen Körpers?','Leber'),
('Wie hieß der erste künstliche Satellit der ins All geschossen wurde?','Sputnik 1'),
('Wie heißt das größte Technologieunternehmen in Südkorea?','Samsung'),
('Was ist die Hauptstadt von Portugal?','Lissabon'),
('Was ist das chemische Symbol für Quecksilber?','Hg'),
('Welcher Monat hat 28 Tage?','Alle'),
('Welcher Kontinent hat keinen aktiven Vulkan?','Australien'),
('Wie heißt der Teufel in Goethes Faust?','Mephistopheles'),
('Welches Tier ist das nationale Symbol von Schottland?','Das Einhorn'),
('Welches Land ist traditionell am meisten Popcorn?','USA'),
('Wie heißt das Baby von einem Schaf?','Lamm'),
('Welche Farbe hat eine Flugzeug-Blackbox?','Orange/Rot'),
('Welcher Vogel legt die größten Eier?','Strauß'),
('Wie nennt man eine Gruppe von Fröschen?','Eine Armee'),
('Welches Land hat die meisten Inseln?','Schweden'),
('Welches Tier kann seinen eigenen Hintern leuchtne lassen?','Glühwürmchen'),
('Welcher Baum produziert Eicheln?','Die Eiche'),
('Wie nennt man das Ergebnis einer Multiplikation?','Produkt'),
('Wie nennt man ein Buch welches eine Sammlung von Karten ist (im Sinne von Weltkarten)?','Atlas'),
('Wann feiern die Amerikaner den Independence Day?','4ter Juli'),
('Wer schrieb das Buch: Der Herr der Ringe?','John Ronald Reuel Tolkien'),
('Welches Werk von Franz Kafka handelt von einem Mann, der eines Morgens erwacht und sich in ein riesiges Ungeziefer verwandelt hat?','Die Verwandlung'),
('Welcher englische Autor ist berühmt für das Werk "1984"?','George Orwell'),
('Welcher Autor erschuf die Figur Sherlock Holmes?','Arthur Conan Doyle'),
('Welche antike Stadt wurde im Jahr 79 n. Chr. durch den Vesuvausbruch zerstört?','Pompeji'),
('Welcher französische Kaiser wurde 1815 in der Schlacht bei Waterloo besiegt?','Napoleon Bonaparte'),
('Wer war der erste Präsident der Vereinigten Staaten von Amerika?','George Washington'),
('Welcher deutsche Reformator veröffentlichte 1517 seine 95 Thesen?','Martin Luther'),
('In welchem Land begann die Industrielle Revolution im 18. Jahrhundert?','England'),
('Welcher mongolische Herrscher eroberte im 13. Jahrhundert weite Teile Asiens und Europas?','Dschingis Khan'),
('Welcher US-Präsident war während des Zweiten Weltkriegs im Amt, bis er 1945 starb?','Franklin D. Roosevelt'),
('Welcher berühmte chinesische Bau erstreckt sich über tausende Kilometer?','Die Chinesische Mauer'),
('Welche Revolution begann 1917 in Russland?','Oktoberrevolution'),
('Wie hieß das Schiff, mit dem Christoph Kolumbus 1492 über den Atlantik segelte?','Santa Maria'),
('Welches Land gewann die erste Fußball-Weltmeisterschaft 1930?','Uruguay'),
('Welcher Physiker entwickelte die Relativitätstheorie?','Albert Einstein'),
('Welcher Musiker wird auch als "King of Pop" bezeichnet?','Michael Jackson'),
('Welcher griechische Philosoph war Lehrer von Alexander dem Großen?','Aristoteles'),
('Welcher Schriftsteller erhielt 1954 den Literaturnobelpreis für "Der alte Mann und das Meer"?','Ernest Hemingway'),
('Welches Jahr markierte den Beginn der Französischen Revolution?','1789'),
('Wie heißt das größte Wüstengebiet der Erde?','Antarktis'),
('Welcher Mathematiker ist berühmt für den Satz über rechtwinklige Dreiecke?','Pythagoras'),
('Welche physikalische Größe wird in der Einheit "Tesla" gemessen?','Magnetische Flussdichte'),
('Welcher deutsche Komponist schrieb die "Ode an die Freude"?','Ludwig van Beethoven'),
('Welche Inselgruppe gehört zu Spanien, liegt aber vor der Küste Afrikas?','Kanarische Inseln'),
('Wie viele Chromosomen hat der Mensch?','46'),
('Welche physikalische Konstante hat den ungefähren Wert 299.792.458 m/s?','Lichtgeschwindigkeit'),
('Wie viele Herzen hat ein Oktopus?','Drei'),
('Welches Tier kann seine Farbe zur Tarnung verändern?','Chamäleon'),
('Welches Säugetier legt Eier?','Schnabeltier'),
('Welches Insekt kann rückwärts fliegen?','Libelle'),
('Welches Tier gilt als das intelligenteste Meeressäugetier?','Delfin'),
('Welches ist das giftigste Tier der Welt?','Würfelqualle'),
('Welches Tier kann seinen eigenen Schwanz bei Gefahr abwerfen?','Eidechse'),
('Welcher Komponist schrieb die Oper "Die Zauberflöte"?','Wolfgang Amadeus Mozart'),
('Welches Instrument spielt man mit einem Bogen?','Geige'),
('Wie heißt der längste Gebirgszug der Welt?','Anden'),
('Welcher deutsche Philosoph schrieb das Werk "Kritik der reinen Vernunft"?','Immanuel Kant'),
('Wie heißt die größte Insel im Mittelmeer?','Sizilien'),
('Wie heißt der längste Fluss in China?','Jangtsekiang'),
('Wie lautet die chemische Formel von Kochsalz?','NaCl'),
('Wer gilt als Erfinder des Buchdrucks in Europa?','Johannes Gutenberg'),
('Wie heißt das größte Korallenriffsystem der Erde?','Great Barrier Reef'),
('Welches Organ im menschlichen Körper filtert das Blut?','Niere'),
('Welcher US-Präsident hielt die berühmte Rede "Ich bin ein Berliner"?','John F. Kennedy'),
('Welcher Vertrag beendete 1919 offiziell den Ersten Weltkrieg?','Vertrag von Versailles'),
('Welche europäische Stadt ist Sitz des Internationalen Gerichtshofs?','Den Haag'),
('Welches Land führte 1917 als erstes das Frauenwahlrecht ein?','Neuseeland'),
('Aus welcher Frucht wird Guacamole hauptsächlich hergestellt?','Avocado'),
('Welches Getränk gilt als das beliebteste weltweit?','Wasser'),
('Wie heißt die traditionelle Kopfbedeckung in Mexiko?','Sombrero'),
('Was ist der Unterschied zwischen grünen und schwarzen Oliven?','Reifegrad'),
('Welches Artefakt sucht Indiana Jones im ersten Indiana Jones Film Jäger des verlorenen Schatzes?','Die Bundeslade'),
('Wo ist die EZB zu finden?','In Frankfurt'),
('Mit einem Schlag einlochen. Wie heißt das beim Golf?','Hole in one'),
('Wie heißt der Rapper Kollegah mit bürgerlichem Namen?','Felix Blume'),
('Wie heißt einer der 2 weißen Zauberer aus Der Herr der Ringe?','Gandalf oder Saruman'),
('Aus welchem Element besteht Diamant?','Kohlenstoff'),
('Mit wem ist Tom Kaulitz verheiratet?','Heidi Klum'),
('Wieviele Buchstaben hat das arabische Alphabet?','28'),
('Welches Land hat 2025 den Eurovision Songcontest gewonnen?','Österreich'),
('Was für Tiere sind Timon und Pumba?','Warzenschwein und Erdmännchen'),
('Was ist neben Sohn und Vater noch Teil der christlichen Dreifaltigkeit?','Heiliger Geist'),
('Welches Land hat neben der Landessprache 21 anerkannte Sprachen?','Indien'),
('Wie ist der Name der Welt in welcher die Diablo Teile spielen?','Sanktuario'),
('Wie oft finden die Wahlen zum europäischem Parlament statt?','Alle 5 Jahre'),
('Wie heißt die Hauptstadt von Ungarn?','Budapest'),
('Wie lautet der Codename von James Bond?','Agent 007'),
('Was ist der nördlichste Staat der USA?','Alaska'),
('Wie heißt der kleine gelbe Roboter der im gleichnamigen Film die Erde aufräumt?','Wall-E'),
('Nenne 2 Tiere der Bremer Stadtmusikanten','(Esel, Hund, Katze, Hahn)'),
('Welcher Schauspieler spielte Captain Jack Sparrow','Johnny Depp'),
('Wie bezeichnet man die Früchte von Rosen?','Hagebutten'),
('Wer war 1903 die erste Frau, die einen Nobelpreis erhielt?','Marie Curie'),
('Die Ermordung von wem löste 1914 den Ersten Weltkrieg aus?','Erzherzog Franz Ferdinand'),
('Welches ist die umsatzstärkste Broadway-Show aller Zeiten?','Der König der Löwen'),
('In welchem Jahr wurde das erste iPhone veröffentlicht?','2007'),
('Welches ist das tödlichste Tier überhaupt?','Die Stechmücke'),
('Was ist die Hauptstadt von Singapur?','Singapur'),
('Wer war in der griechischen Mythologie als Götterbote bekannt?','Hermes'),
('In welcher Stadt wurden die ersten Infektionen mit COVID-19 entdeckt?','Wuhan, China'),
('In welche Richtung kann ein Läufer beim Schach ziehen?','schräg/diagonal'),
('Nach welcher Sängerin wurde 1996 das erste geklonte Tier der Welt, ein Schaf, benannt?','Dolly Parton'),
('Wie viele Farben findet man in einer normalen Tüte M&Ms?','Sechs'),
('Die Freiheitsstatue war ein Geschenk an die USA von welchem Land?','Frankreich'),
('Was ist die seltenste Blutgruppe?','AB negativ'),
('Welches alkoholische Getränk wird aus Wacholderbeeren hergestellt?','Gin'),
('Welches Land hat die höchste Anzahl von Bürgern über 65 Jahren?','Japan'),
('Welches ist die am längsten laufende amerikanische Zeichentrickserie im Fernsehen?','Die Simpsons'),
('Wo im menschlichen Körper befindet sich der kleinste Knochen?','Im Ohr'),
('Wo lebten Winnie the Pooh und seine Mannschaft, die als Schauplatz für ihre Abenteuer mit Christopher Robin diente?','Im Hundertmorgenwald'),
('Wer komponierte die "Mondscheinsonate"?','Ludwig van Beethoven'),
('Welche Farbe ist das Gegenteil von Blau auf dem Farbkreis?','Orange'),
('Wie heißt das fermentierte Kohlgericht, das in der koreanischen Küche ein Grundnahrungsmittel ist?','Kimchi'),
('Wie lautete der bekanntere Name der als Norma Jeane Mortenson geborenen Schauspielerin?','Marilyn Monroe'),
('Welcher Buch- und Film-Bestseller wurde ursprünglich als "Twilight"-Fanfiction unter dem Pseudonym Snowqueen Icedragon verfasst?','50 Shades of Grey'),
('Wie heißt die fiktive afrikanische Nation, die in dem Marvel-Film "Black Panther" dargestellt wird?','Wakanda'),
('Was ist eine Primzahl?','Eine Zahl größer 1, die nur durch 1 und sich selbst teilbar ist.'),
('Mit wie vielen Figuren startet ein Schachspiel?','32'),
('Welchen Aggregatzustand hat der innere Erdkern?','fest');

